version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: travel-pricing-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel_pricing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d travel_pricing"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    container_name: travel-pricing-api
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/travel_pricing
      API_HOST: 0.0.0.0
      API_PORT: 8000
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../data:/app/data
      - ../../core:/app/core
      - ../../apps:/app/apps

volumes:
  postgres_data:
