apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrichment-worker
  namespace: jengu
  labels:
    app: enrichment-worker
    component: queue-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enrichment-worker
  template:
    metadata:
      labels:
        app: enrichment-worker
        component: queue-worker
    spec:
      containers:
        - name: enrichment-worker
          image: jengu/backend:latest
          command: ['node', 'dist/workers/enrichmentWorker.js']
          env:
            - name: NODE_ENV
              value: 'production'
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: jengu-secrets
                  key: redis-url
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: jengu-secrets
                  key: supabase-url
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: jengu-secrets
                  key: supabase-service-key
            - name: ENRICHMENT_WORKER_CONCURRENCY
              value: '5'
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jengu-secrets
                  key: anthropic-api-key
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jengu-secrets
                  key: openweather-api-key
                  optional: true
            - name: CALENDARIFIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jengu-secrets
                  key: calendarific-api-key
                  optional: true
            - name: ENABLE_AUTO_ANALYTICS
              value: 'true'
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1000m'
          livenessProbe:
            exec:
              command:
                - node
                - -e
                - 'process.exit(0)'
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - node
                - -e
                - 'process.exit(0)'
            initialDelaySeconds: 10
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: enrichment-worker-hpa
  namespace: jengu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enrichment-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    # Scale based on queue depth (custom metric from Prometheus)
    - type: External
      external:
        metric:
          name: bullmq_queue_waiting_jobs
          selector:
            matchLabels:
              queue: enrichment
        target:
          type: AverageValue
          averageValue: '10' # Scale up if avg waiting jobs > 10
    # Scale based on CPU usage
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # Scale based on memory usage
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 minutes before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
